[server]
headless = true

[theme]
primaryColor = "#00A884"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
favicon = "favicon.ico"
